players:
  - crewmate_BDI_1
  - crewmate_BDI_2
  - crewmate_BDI_3
  - crewmate_BDI_4
  - crewmate_BDI_5
  - crewmate_BDI_6
  - crewmate_BDI_7
  - crewmate_BDI_8
  - impostor_BDI_1
  - impostor_BDI_2
  - impostor_BDI_3
  - impostor_BDI_4

crewmate_skill:
  crewmate_BDI_1: 0.55
  crewmate_BDI_2: 0.55
  crewmate_BDI_3: 0.55
  crewmate_BDI_4: 0.55
  crewmate_BDI_5: 0.55
  crewmate_BDI_6: 0.55
  crewmate_BDI_7: 0.55
  crewmate_BDI_8: 0.55

impostor_behavior:
  impostor_BDI_1: methodical
  impostor_BDI_2: methodical
  impostor_BDI_3: methodical
  impostor_BDI_4: methodical

colors:
  - red
  - blue
  - green
  - yellow
  - pink
  - orange
  - black
  - white
  - purple
  - brown
  - cyan
  - lime

player_color:
  crewmate_BDI_1: random
  crewmate_BDI_2: random
  crewmate_BDI_3: random
  crewmate_BDI_4: random
  crewmate_BDI_5: random
  crewmate_BDI_6: random
  crewmate_BDI_7: random
  crewmate_BDI_8: random
  impostor_BDI_1: random
  impostor_BDI_2: random
  impostor_BDI_3: random
  impostor_BDI_4: random

rooms:
  section_1: 6
  section_2: 6
  section_3: 6
  section_4: 6
  section_5: 6

initial_room:
  crewmate_BDI_1: random
  crewmate_BDI_2: random
  crewmate_BDI_3: random
  crewmate_BDI_4: random
  crewmate_BDI_5: random
  crewmate_BDI_6: random
  crewmate_BDI_7: random
  crewmate_BDI_8: random
  impostor_BDI_1: random
  impostor_BDI_2: random
  impostor_BDI_3: random
  impostor_BDI_4: random